# coding: utf-8

"""
    Algod REST API.

    API endpoint for algod operations.

    The version of the OpenAPI document: 0.0.1
    Contact: contact@algorand.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from algokit_algod_api.models.asset_holding import AssetHolding
from algokit_algod_api.models.asset_params import AssetParams
from typing import Optional, Set
from typing_extensions import Self

class AccountAssetHolding(BaseModel):
    """
    AccountAssetHolding describes the account's asset holding and asset parameters (if either exist) for a specific asset ID.
    """ # noqa: E501
    asset_holding: AssetHolding = Field(alias="asset-holding")
    asset_params: Optional[AssetParams] = Field(default=None, alias="asset-params")
    __properties: ClassVar[List[str]] = ["asset-holding", "asset-params"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AccountAssetHolding from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of asset_holding
        if self.asset_holding:
            _dict['asset-holding'] = self.asset_holding.to_dict()
        # override the default output from pydantic by calling `to_dict()` of asset_params
        if self.asset_params:
            _dict['asset-params'] = self.asset_params.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AccountAssetHolding from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "asset-holding": AssetHolding.from_dict(obj["asset-holding"]) if obj.get("asset-holding") is not None else None,
            "asset-params": AssetParams.from_dict(obj["asset-params"]) if obj.get("asset-params") is not None else None
        })
        return _obj


