# coding: utf-8

"""
    Algod REST API.

    API endpoint for algod operations.

    The version of the OpenAPI document: 0.0.1
    Contact: contact@algorand.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from algokit_algod_api.models.account_asset_holding import AccountAssetHolding
from typing import Optional, Set
from typing_extensions import Self

class AccountAssetsInformation200Response(BaseModel):
    """
    AccountAssetsInformation200Response
    """ # noqa: E501
    round: StrictInt = Field(description="The round for which this information is relevant.")
    next_token: Optional[StrictStr] = Field(default=None, description="Used for pagination, when making another request provide this token with the next parameter.", alias="next-token")
    asset_holdings: Optional[List[AccountAssetHolding]] = Field(default=None, alias="asset-holdings")
    __properties: ClassVar[List[str]] = ["round", "next-token", "asset-holdings"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AccountAssetsInformation200Response from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in asset_holdings (list)
        _items = []
        if self.asset_holdings:
            for _item_asset_holdings in self.asset_holdings:
                if _item_asset_holdings:
                    _items.append(_item_asset_holdings.to_dict())
            _dict['asset-holdings'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AccountAssetsInformation200Response from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "round": obj.get("round"),
            "next-token": obj.get("next-token"),
            "asset-holdings": [AccountAssetHolding.from_dict(_item) for _item in obj["asset-holdings"]] if obj.get("asset-holdings") is not None else None
        })
        return _obj


