# coding: utf-8

"""
    Algod REST API.

    API endpoint for algod operations.

    The version of the OpenAPI document: 0.0.1
    Contact: contact@algorand.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class SimulateTraceConfig(BaseModel):
    """
    An object that configures simulation execution trace.
    """ # noqa: E501
    enable: Optional[StrictBool] = Field(default=None, description="A boolean option for opting in execution trace features simulation endpoint.")
    stack_change: Optional[StrictBool] = Field(default=None, description="A boolean option enabling returning stack changes together with execution trace during simulation.", alias="stack-change")
    scratch_change: Optional[StrictBool] = Field(default=None, description="A boolean option enabling returning scratch slot changes together with execution trace during simulation.", alias="scratch-change")
    state_change: Optional[StrictBool] = Field(default=None, description="A boolean option enabling returning application state changes (global, local, and box changes) with the execution trace during simulation.", alias="state-change")
    __properties: ClassVar[List[str]] = ["enable", "stack-change", "scratch-change", "state-change"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SimulateTraceConfig from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SimulateTraceConfig from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "enable": obj.get("enable"),
            "stack-change": obj.get("stack-change"),
            "scratch-change": obj.get("scratch-change"),
            "state-change": obj.get("state-change")
        })
        return _obj


