/**
 * Algod REST API.
 * API endpoint for algod operations.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: contact@algorand.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* An catchpoint abort response.
*/
export class AbortCatchup200Response {
    /**
    * Catchup abort response string
    */
    'catchupMessage': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "catchupMessage",
            "baseName": "catchup-message",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AbortCatchup200Response.attributeTypeMap;
    }

    public constructor() {
    }
}
