/**
 * Algod REST API.
 * API endpoint for algod operations.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: contact@algorand.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AssetHolding } from '../models/AssetHolding';
import { AssetParams } from '../models/AssetParams';
import { HttpFile } from '../http/http';

/**
* AccountAssetHolding describes the account\'s asset holding and asset parameters (if either exist) for a specific asset ID.
*/
export class AccountAssetHolding {
    'assetHolding': AssetHolding;
    'assetParams'?: AssetParams;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "assetHolding",
            "baseName": "asset-holding",
            "type": "AssetHolding",
            "format": ""
        },
        {
            "name": "assetParams",
            "baseName": "asset-params",
            "type": "AssetParams",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AccountAssetHolding.attributeTypeMap;
    }

    public constructor() {
    }
}
