/**
 * Algod REST API.
 * API endpoint for algod operations.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: contact@algorand.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ApplicationLocalState } from '../models/ApplicationLocalState';
import { ApplicationParams } from '../models/ApplicationParams';
import { HttpFile } from '../http/http';

export class AccountApplicationInformation200Response {
    /**
    * The round for which this information is relevant.
    */
    'round': number;
    'appLocalState'?: ApplicationLocalState;
    'createdApp'?: ApplicationParams;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "round",
            "baseName": "round",
            "type": "number",
            "format": ""
        },
        {
            "name": "appLocalState",
            "baseName": "app-local-state",
            "type": "ApplicationLocalState",
            "format": ""
        },
        {
            "name": "createdApp",
            "baseName": "created-app",
            "type": "ApplicationParams",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AccountApplicationInformation200Response.attributeTypeMap;
    }

    public constructor() {
    }
}
