/**
 * Algod REST API.
 * API endpoint for algod operations.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: contact@algorand.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AccountAssetHolding } from '../models/AccountAssetHolding';
import { HttpFile } from '../http/http';

export class AccountAssetsInformation200Response {
    /**
    * The round for which this information is relevant.
    */
    'round': number;
    /**
    * Used for pagination, when making another request provide this token with the next parameter.
    */
    'nextToken'?: string;
    'assetHoldings'?: Array<AccountAssetHolding>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "round",
            "baseName": "round",
            "type": "number",
            "format": ""
        },
        {
            "name": "nextToken",
            "baseName": "next-token",
            "type": "string",
            "format": ""
        },
        {
            "name": "assetHoldings",
            "baseName": "asset-holdings",
            "type": "Array<AccountAssetHolding>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AccountAssetsInformation200Response.attributeTypeMap;
    }

    public constructor() {
    }
}
