/**
 * Algod REST API.
 * API endpoint for algod operations.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: contact@algorand.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { EvalDeltaKeyValue } from '../models/EvalDeltaKeyValue';
import { HttpFile } from '../http/http';

/**
* Application state delta.
*/
export class AccountStateDelta {
    'address': string;
    /**
    * Application state delta.
    */
    'delta': Array<EvalDeltaKeyValue>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "address",
            "baseName": "address",
            "type": "string",
            "format": ""
        },
        {
            "name": "delta",
            "baseName": "delta",
            "type": "Array<EvalDeltaKeyValue>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AccountStateDelta.attributeTypeMap;
    }

    public constructor() {
    }
}
