/**
 * Algod REST API.
 * API endpoint for algod operations.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: contact@algorand.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* AccountParticipation describes the parameters used by this account in consensus protocol.
*/
export class AccountParticipation {
    /**
    * \\[sel\\] Selection public key (if any) currently registered for this round.
    */
    'selectionParticipationKey': string;
    /**
    * \\[voteFst\\] First round for which this participation is valid.
    */
    'voteFirstValid': number;
    /**
    * \\[voteKD\\] Number of subkeys in each batch of participation keys.
    */
    'voteKeyDilution': number;
    /**
    * \\[voteLst\\] Last round for which this participation is valid.
    */
    'voteLastValid': number;
    /**
    * \\[vote\\] root participation public key (if any) currently registered for this round.
    */
    'voteParticipationKey': string;
    /**
    * \\[stprf\\] Root of the state proof key (if any)
    */
    'stateProofKey'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "selectionParticipationKey",
            "baseName": "selection-participation-key",
            "type": "string",
            "format": "byte"
        },
        {
            "name": "voteFirstValid",
            "baseName": "vote-first-valid",
            "type": "number",
            "format": ""
        },
        {
            "name": "voteKeyDilution",
            "baseName": "vote-key-dilution",
            "type": "number",
            "format": ""
        },
        {
            "name": "voteLastValid",
            "baseName": "vote-last-valid",
            "type": "number",
            "format": ""
        },
        {
            "name": "voteParticipationKey",
            "baseName": "vote-participation-key",
            "type": "string",
            "format": "byte"
        },
        {
            "name": "stateProofKey",
            "baseName": "state-proof-key",
            "type": "string",
            "format": "byte"
        }    ];

    static getAttributeTypeMap() {
        return AccountParticipation.attributeTypeMap;
    }

    public constructor() {
    }
}
