/**
 * Algod REST API.
 * API endpoint for algod operations.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: contact@algorand.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AccountParticipation } from '../models/AccountParticipation';
import { Application } from '../models/Application';
import { ApplicationLocalState } from '../models/ApplicationLocalState';
import { ApplicationStateSchema } from '../models/ApplicationStateSchema';
import { Asset } from '../models/Asset';
import { AssetHolding } from '../models/AssetHolding';
import { HttpFile } from '../http/http';

/**
* Account information at a given round.  Definition: data/basics/userBalance.go : AccountData 
*/
export class Account {
    /**
    * the account public key
    */
    'address': string;
    /**
    * \\[algo\\] total number of MicroAlgos in the account
    */
    'amount': number;
    /**
    * MicroAlgo balance required by the account.  The requirement grows based on asset and application usage.
    */
    'minBalance': number;
    /**
    * specifies the amount of MicroAlgos in the account, without the pending rewards.
    */
    'amountWithoutPendingRewards': number;
    /**
    * \\[appl\\] applications local data stored in this account.  Note the raw object uses `map[int] -> AppLocalState` for this type.
    */
    'appsLocalState'?: Array<ApplicationLocalState>;
    /**
    * The count of all applications that have been opted in, equivalent to the count of application local data (AppLocalState objects) stored in this account.
    */
    'totalAppsOptedIn': number;
    'appsTotalSchema'?: ApplicationStateSchema;
    /**
    * \\[teap\\] the sum of all extra application program pages for this account.
    */
    'appsTotalExtraPages'?: number;
    /**
    * \\[asset\\] assets held by this account.  Note the raw object uses `map[int] -> AssetHolding` for this type.
    */
    'assets'?: Array<AssetHolding>;
    /**
    * The count of all assets that have been opted in, equivalent to the count of AssetHolding objects held by this account.
    */
    'totalAssetsOptedIn': number;
    /**
    * \\[appp\\] parameters of applications created by this account including app global data.  Note: the raw account uses `map[int] -> AppParams` for this type.
    */
    'createdApps'?: Array<Application>;
    /**
    * The count of all apps (AppParams objects) created by this account.
    */
    'totalCreatedApps': number;
    /**
    * \\[apar\\] parameters of assets created by this account.  Note: the raw account uses `map[int] -> Asset` for this type.
    */
    'createdAssets'?: Array<Asset>;
    /**
    * The count of all assets (AssetParams objects) created by this account.
    */
    'totalCreatedAssets': number;
    /**
    * \\[tbx\\] The number of existing boxes created by this account\'s app.
    */
    'totalBoxes'?: number;
    /**
    * \\[tbxb\\] The total number of bytes used by this account\'s app\'s box keys and values.
    */
    'totalBoxBytes'?: number;
    'participation'?: AccountParticipation;
    /**
    * Whether or not the account can receive block incentives if its balance is in range at proposal time.
    */
    'incentiveEligible'?: boolean;
    /**
    * amount of MicroAlgos of pending rewards in this account.
    */
    'pendingRewards': number;
    /**
    * \\[ebase\\] used as part of the rewards computation. Only applicable to accounts which are participating.
    */
    'rewardBase'?: number;
    /**
    * \\[ern\\] total rewards of MicroAlgos the account has received, including pending rewards.
    */
    'rewards': number;
    /**
    * The round for which this information is relevant.
    */
    'round': number;
    /**
    * \\[onl\\] delegation status of the account\'s MicroAlgos * Offline - indicates that the associated account is delegated. *  Online  - indicates that the associated account used as part of the delegation pool. *   NotParticipating - indicates that the associated account is neither a delegator nor a delegate.
    */
    'status': string;
    /**
    * Indicates what type of signature is used by this account, must be one of: * sig * msig * lsig
    */
    'sigType'?: AccountSigTypeEnum;
    /**
    * \\[spend\\] the address against which signing should be checked. If empty, the address of the current account is used. This field can be updated in any transaction by setting the RekeyTo field.
    */
    'authAddr'?: string;
    /**
    * The round in which this account last proposed the block.
    */
    'lastProposed'?: number;
    /**
    * The round in which this account last went online, or explicitly renewed their online status.
    */
    'lastHeartbeat'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "address",
            "baseName": "address",
            "type": "string",
            "format": ""
        },
        {
            "name": "amount",
            "baseName": "amount",
            "type": "number",
            "format": ""
        },
        {
            "name": "minBalance",
            "baseName": "min-balance",
            "type": "number",
            "format": ""
        },
        {
            "name": "amountWithoutPendingRewards",
            "baseName": "amount-without-pending-rewards",
            "type": "number",
            "format": ""
        },
        {
            "name": "appsLocalState",
            "baseName": "apps-local-state",
            "type": "Array<ApplicationLocalState>",
            "format": ""
        },
        {
            "name": "totalAppsOptedIn",
            "baseName": "total-apps-opted-in",
            "type": "number",
            "format": ""
        },
        {
            "name": "appsTotalSchema",
            "baseName": "apps-total-schema",
            "type": "ApplicationStateSchema",
            "format": ""
        },
        {
            "name": "appsTotalExtraPages",
            "baseName": "apps-total-extra-pages",
            "type": "number",
            "format": ""
        },
        {
            "name": "assets",
            "baseName": "assets",
            "type": "Array<AssetHolding>",
            "format": ""
        },
        {
            "name": "totalAssetsOptedIn",
            "baseName": "total-assets-opted-in",
            "type": "number",
            "format": ""
        },
        {
            "name": "createdApps",
            "baseName": "created-apps",
            "type": "Array<Application>",
            "format": ""
        },
        {
            "name": "totalCreatedApps",
            "baseName": "total-created-apps",
            "type": "number",
            "format": ""
        },
        {
            "name": "createdAssets",
            "baseName": "created-assets",
            "type": "Array<Asset>",
            "format": ""
        },
        {
            "name": "totalCreatedAssets",
            "baseName": "total-created-assets",
            "type": "number",
            "format": ""
        },
        {
            "name": "totalBoxes",
            "baseName": "total-boxes",
            "type": "number",
            "format": ""
        },
        {
            "name": "totalBoxBytes",
            "baseName": "total-box-bytes",
            "type": "number",
            "format": ""
        },
        {
            "name": "participation",
            "baseName": "participation",
            "type": "AccountParticipation",
            "format": ""
        },
        {
            "name": "incentiveEligible",
            "baseName": "incentive-eligible",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "pendingRewards",
            "baseName": "pending-rewards",
            "type": "number",
            "format": ""
        },
        {
            "name": "rewardBase",
            "baseName": "reward-base",
            "type": "number",
            "format": ""
        },
        {
            "name": "rewards",
            "baseName": "rewards",
            "type": "number",
            "format": ""
        },
        {
            "name": "round",
            "baseName": "round",
            "type": "number",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "string",
            "format": ""
        },
        {
            "name": "sigType",
            "baseName": "sig-type",
            "type": "AccountSigTypeEnum",
            "format": ""
        },
        {
            "name": "authAddr",
            "baseName": "auth-addr",
            "type": "string",
            "format": ""
        },
        {
            "name": "lastProposed",
            "baseName": "last-proposed",
            "type": "number",
            "format": ""
        },
        {
            "name": "lastHeartbeat",
            "baseName": "last-heartbeat",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Account.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum AccountSigTypeEnum {
    Sig = 'sig',
    Msig = 'msig',
    Lsig = 'lsig'
}

