/**
 * Algod REST API.
 * API endpoint for algod operations.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: contact@algorand.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* The logged messages from an app call along with the app ID and outer transaction ID. Logs appear in the same order that they were emitted.
*/
export class AppCallLogs {
    /**
    * An array of logs
    */
    'logs': Array<string>;
    /**
    * The application from which the logs were generated
    */
    'applicationIndex': number;
    /**
    * The transaction ID of the outer app call that lead to these logs
    */
    'txId': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "logs",
            "baseName": "logs",
            "type": "Array<string>",
            "format": "byte"
        },
        {
            "name": "applicationIndex",
            "baseName": "application-index",
            "type": "number",
            "format": ""
        },
        {
            "name": "txId",
            "baseName": "txId",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AppCallLogs.attributeTypeMap;
    }

    public constructor() {
    }
}
