/**
 * Algod REST API.
 * API endpoint for algod operations.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: contact@algorand.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Specifies maximums on the number of each type that may be stored.
*/
export class ApplicationStateSchema {
    /**
    * \\[nui\\] num of uints.
    */
    'numUint': number;
    /**
    * \\[nbs\\] num of byte slices.
    */
    'numByteSlice': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "numUint",
            "baseName": "num-uint",
            "type": "number",
            "format": ""
        },
        {
            "name": "numByteSlice",
            "baseName": "num-byte-slice",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ApplicationStateSchema.attributeTypeMap;
    }

    public constructor() {
    }
}
