/**
 * Algod REST API.
 * API endpoint for algod operations.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: contact@algorand.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AvmKeyValue } from '../models/AvmKeyValue';
import { HttpFile } from '../http/http';

/**
* An application\'s global/local/box state.
*/
export class ApplicationKVStorage {
    /**
    * Key-Value pairs representing application states.
    */
    'kvs': Array<AvmKeyValue>;
    /**
    * The address of the account associated with the local state.
    */
    'account'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "kvs",
            "baseName": "kvs",
            "type": "Array<AvmKeyValue>",
            "format": ""
        },
        {
            "name": "account",
            "baseName": "account",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ApplicationKVStorage.attributeTypeMap;
    }

    public constructor() {
    }
}
