/**
 * Algod REST API.
 * API endpoint for algod operations.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: contact@algorand.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ApplicationStateSchema } from '../models/ApplicationStateSchema';
import { TealKeyValue } from '../models/TealKeyValue';
import { HttpFile } from '../http/http';

/**
* Stores local state associated with an application.
*/
export class ApplicationLocalState {
    /**
    * The application which this local state is for.
    */
    'id': number;
    'schema': ApplicationStateSchema;
    /**
    * Represents a key-value store for use in an application.
    */
    'keyValue'?: Array<TealKeyValue>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": ""
        },
        {
            "name": "schema",
            "baseName": "schema",
            "type": "ApplicationStateSchema",
            "format": ""
        },
        {
            "name": "keyValue",
            "baseName": "key-value",
            "type": "Array<TealKeyValue>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ApplicationLocalState.attributeTypeMap;
    }

    public constructor() {
    }
}
