/**
 * Algod REST API.
 * API endpoint for algod operations.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: contact@algorand.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ApplicationParams } from '../models/ApplicationParams';
import { HttpFile } from '../http/http';

/**
* Application index and its parameters
*/
export class Application {
    /**
    * \\[appidx\\] application index.
    */
    'id': number;
    'params': ApplicationParams;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": ""
        },
        {
            "name": "params",
            "baseName": "params",
            "type": "ApplicationParams",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Application.attributeTypeMap;
    }

    public constructor() {
    }
}
