/**
 * Algod REST API.
 * API endpoint for algod operations.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: contact@algorand.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AvmValue } from '../models/AvmValue';
import { HttpFile } from '../http/http';

/**
* An operation against an application\'s global/local/box state.
*/
export class ApplicationStateOperation {
    /**
    * Operation type. Value `w` is **write**, `d` is **delete**.
    */
    'operation': string;
    /**
    * Type of application state. Value `g` is **global state**, `l` is **local state**, `b` is **boxes**.
    */
    'appStateType': string;
    /**
    * The key (name) of the global/local/box state.
    */
    'key': string;
    'newValue'?: AvmValue;
    /**
    * For local state changes, the address of the account associated with the local state.
    */
    'account'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "operation",
            "baseName": "operation",
            "type": "string",
            "format": ""
        },
        {
            "name": "appStateType",
            "baseName": "app-state-type",
            "type": "string",
            "format": ""
        },
        {
            "name": "key",
            "baseName": "key",
            "type": "string",
            "format": "byte"
        },
        {
            "name": "newValue",
            "baseName": "new-value",
            "type": "AvmValue",
            "format": ""
        },
        {
            "name": "account",
            "baseName": "account",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ApplicationStateOperation.attributeTypeMap;
    }

    public constructor() {
    }
}
