/**
 * Algod REST API.
 * API endpoint for algod operations.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: contact@algorand.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ApplicationKVStorage } from '../models/ApplicationKVStorage';
import { HttpFile } from '../http/http';

/**
* An application\'s initial global/local/box states that were accessed during simulation.
*/
export class ApplicationInitialStates {
    /**
    * Application index.
    */
    'id': number;
    /**
    * An application\'s initial local states tied to different accounts.
    */
    'appLocals'?: Array<ApplicationKVStorage>;
    'appGlobals'?: ApplicationKVStorage;
    'appBoxes'?: ApplicationKVStorage;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": ""
        },
        {
            "name": "appLocals",
            "baseName": "app-locals",
            "type": "Array<ApplicationKVStorage>",
            "format": ""
        },
        {
            "name": "appGlobals",
            "baseName": "app-globals",
            "type": "ApplicationKVStorage",
            "format": ""
        },
        {
            "name": "appBoxes",
            "baseName": "app-boxes",
            "type": "ApplicationKVStorage",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ApplicationInitialStates.attributeTypeMap;
    }

    public constructor() {
    }
}
