/**
 * Algod REST API.
 * API endpoint for algod operations.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: contact@algorand.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ApplicationStateSchema } from '../models/ApplicationStateSchema';
import { TealKeyValue } from '../models/TealKeyValue';
import { HttpFile } from '../http/http';

/**
* Stores the global information associated with an application.
*/
export class ApplicationParams {
    /**
    * The address that created this application. This is the address where the parameters and global state for this application can be found.
    */
    'creator': string;
    /**
    * \\[approv\\] approval program.
    */
    'approvalProgram': string;
    /**
    * \\[clearp\\] approval program.
    */
    'clearStateProgram': string;
    /**
    * \\[epp\\] the amount of extra program pages available to this app.
    */
    'extraProgramPages'?: number;
    'localStateSchema'?: ApplicationStateSchema;
    'globalStateSchema'?: ApplicationStateSchema;
    /**
    * Represents a key-value store for use in an application.
    */
    'globalState'?: Array<TealKeyValue>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "creator",
            "baseName": "creator",
            "type": "string",
            "format": ""
        },
        {
            "name": "approvalProgram",
            "baseName": "approval-program",
            "type": "string",
            "format": "byte"
        },
        {
            "name": "clearStateProgram",
            "baseName": "clear-state-program",
            "type": "string",
            "format": "byte"
        },
        {
            "name": "extraProgramPages",
            "baseName": "extra-program-pages",
            "type": "number",
            "format": ""
        },
        {
            "name": "localStateSchema",
            "baseName": "local-state-schema",
            "type": "ApplicationStateSchema",
            "format": ""
        },
        {
            "name": "globalStateSchema",
            "baseName": "global-state-schema",
            "type": "ApplicationStateSchema",
            "format": ""
        },
        {
            "name": "globalState",
            "baseName": "global-state",
            "type": "Array<TealKeyValue>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ApplicationParams.attributeTypeMap;
    }

    public constructor() {
    }
}
