/**
 * Algod REST API.
 * API endpoint for algod operations.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: contact@algorand.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AssetParams } from '../models/AssetParams';
import { HttpFile } from '../http/http';

/**
* Specifies both the unique identifier and the parameters for an asset
*/
export class Asset {
    /**
    * unique asset identifier
    */
    'index': number;
    'params': AssetParams;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "index",
            "baseName": "index",
            "type": "number",
            "format": ""
        },
        {
            "name": "params",
            "baseName": "params",
            "type": "AssetParams",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Asset.attributeTypeMap;
    }

    public constructor() {
    }
}
