/**
 * Algod REST API.
 * API endpoint for algod operations.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: contact@algorand.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* References an asset held by an account.
*/
export class AssetHoldingReference {
    /**
    * Address of the account holding the asset.
    */
    'account': string;
    /**
    * Asset ID of the holding.
    */
    'asset': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "account",
            "baseName": "account",
            "type": "string",
            "format": ""
        },
        {
            "name": "asset",
            "baseName": "asset",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AssetHoldingReference.attributeTypeMap;
    }

    public constructor() {
    }
}
