/**
 * Algod REST API.
 * API endpoint for algod operations.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: contact@algorand.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* AssetParams specifies the parameters for an asset.  \\[apar\\] when part of an AssetConfig transaction.  Definition: data/transactions/asset.go : AssetParams
*/
export class AssetParams {
    /**
    * \\[c\\] Address of account used to clawback holdings of this asset.  If empty, clawback is not permitted.
    */
    'clawback'?: string;
    /**
    * The address that created this asset. This is the address where the parameters for this asset can be found, and also the address where unwanted asset units can be sent in the worst case.
    */
    'creator': string;
    /**
    * \\[dc\\] The number of digits to use after the decimal point when displaying this asset. If 0, the asset is not divisible. If 1, the base unit of the asset is in tenths. If 2, the base unit of the asset is in hundredths, and so on. This value must be between 0 and 19 (inclusive).
    */
    'decimals': number;
    /**
    * \\[df\\] Whether holdings of this asset are frozen by default.
    */
    'defaultFrozen'?: boolean;
    /**
    * \\[f\\] Address of account used to freeze holdings of this asset.  If empty, freezing is not permitted.
    */
    'freeze'?: string;
    /**
    * \\[m\\] Address of account used to manage the keys of this asset and to destroy it.
    */
    'manager'?: string;
    /**
    * \\[am\\] A commitment to some unspecified asset metadata. The format of this metadata is up to the application.
    */
    'metadataHash'?: string;
    /**
    * \\[an\\] Name of this asset, as supplied by the creator. Included only when the asset name is composed of printable utf-8 characters.
    */
    'name'?: string;
    /**
    * Base64 encoded name of this asset, as supplied by the creator.
    */
    'nameB64'?: string;
    /**
    * \\[r\\] Address of account holding reserve (non-minted) units of this asset.
    */
    'reserve'?: string;
    /**
    * \\[t\\] The total number of units of this asset.
    */
    'total': number;
    /**
    * \\[un\\] Name of a unit of this asset, as supplied by the creator. Included only when the name of a unit of this asset is composed of printable utf-8 characters.
    */
    'unitName'?: string;
    /**
    * Base64 encoded name of a unit of this asset, as supplied by the creator.
    */
    'unitNameB64'?: string;
    /**
    * \\[au\\] URL where more information about the asset can be retrieved. Included only when the URL is composed of printable utf-8 characters.
    */
    'url'?: string;
    /**
    * Base64 encoded URL where more information about the asset can be retrieved.
    */
    'urlB64'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "clawback",
            "baseName": "clawback",
            "type": "string",
            "format": ""
        },
        {
            "name": "creator",
            "baseName": "creator",
            "type": "string",
            "format": ""
        },
        {
            "name": "decimals",
            "baseName": "decimals",
            "type": "number",
            "format": ""
        },
        {
            "name": "defaultFrozen",
            "baseName": "default-frozen",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "freeze",
            "baseName": "freeze",
            "type": "string",
            "format": ""
        },
        {
            "name": "manager",
            "baseName": "manager",
            "type": "string",
            "format": ""
        },
        {
            "name": "metadataHash",
            "baseName": "metadata-hash",
            "type": "string",
            "format": "byte"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "nameB64",
            "baseName": "name-b64",
            "type": "string",
            "format": "byte"
        },
        {
            "name": "reserve",
            "baseName": "reserve",
            "type": "string",
            "format": ""
        },
        {
            "name": "total",
            "baseName": "total",
            "type": "number",
            "format": ""
        },
        {
            "name": "unitName",
            "baseName": "unit-name",
            "type": "string",
            "format": ""
        },
        {
            "name": "unitNameB64",
            "baseName": "unit-name-b64",
            "type": "string",
            "format": "byte"
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string",
            "format": ""
        },
        {
            "name": "urlB64",
            "baseName": "url-b64",
            "type": "string",
            "format": "byte"
        }    ];

    static getAttributeTypeMap() {
        return AssetParams.attributeTypeMap;
    }

    public constructor() {
    }
}
