/**
 * Algod REST API.
 * API endpoint for algod operations.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: contact@algorand.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Represents an AVM value.
*/
export class AvmValue {
    /**
    * value type. Value `1` refers to **bytes**, value `2` refers to **uint64**
    */
    'type': number;
    /**
    * bytes value.
    */
    'bytes'?: string;
    /**
    * uint value.
    */
    'uint'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "number",
            "format": ""
        },
        {
            "name": "bytes",
            "baseName": "bytes",
            "type": "string",
            "format": ""
        },
        {
            "name": "uint",
            "baseName": "uint",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AvmValue.attributeTypeMap;
    }

    public constructor() {
    }
}
