/**
 * Algod REST API.
 * API endpoint for algod operations.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: contact@algorand.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class BuildVersion {
    'branch': string;
    'buildNumber': number;
    'channel': string;
    'commitHash': string;
    'major': number;
    'minor': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "branch",
            "baseName": "branch",
            "type": "string",
            "format": ""
        },
        {
            "name": "buildNumber",
            "baseName": "build_number",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "channel",
            "baseName": "channel",
            "type": "string",
            "format": ""
        },
        {
            "name": "commitHash",
            "baseName": "commit_hash",
            "type": "string",
            "format": ""
        },
        {
            "name": "major",
            "baseName": "major",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "minor",
            "baseName": "minor",
            "type": "number",
            "format": "int64"
        }    ];

    static getAttributeTypeMap() {
        return BuildVersion.attributeTypeMap;
    }

    public constructor() {
    }
}
