/**
 * Algod REST API.
 * API endpoint for algod operations.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: contact@algorand.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* algod mutex and blocking profiling state.
*/
export class DebugSettingsProf {
    /**
    * The rate of blocking events. The profiler aims to sample an average of one blocking event per rate nanoseconds spent blocked. To turn off profiling entirely, pass rate 0.
    */
    'blockRate'?: number;
    /**
    * The rate of mutex events. On average 1/rate events are reported. To turn off profiling entirely, pass rate 0
    */
    'mutexRate'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "blockRate",
            "baseName": "block-rate",
            "type": "number",
            "format": ""
        },
        {
            "name": "mutexRate",
            "baseName": "mutex-rate",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return DebugSettingsProf.attributeTypeMap;
    }

    public constructor() {
    }
}
