/**
 * Algod REST API.
 * API endpoint for algod operations.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: contact@algorand.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Account } from '../models/Account';
import { Application } from '../models/Application';
import { DryrunSource } from '../models/DryrunSource';
import { HttpFile } from '../http/http';

/**
* Request data type for dryrun endpoint. Given the Transactions and simulated ledger state upload, run TEAL scripts and return debugging information.
*/
export class DryrunRequest {
    'txns': Array<string>;
    'accounts': Array<Account>;
    'apps': Array<Application>;
    /**
    * ProtocolVersion specifies a specific version string to operate under, otherwise whatever the current protocol of the network this algod is running in.
    */
    'protocolVersion': string;
    /**
    * Round is available to some TEAL scripts. Defaults to the current round on the network this algod is attached to.
    */
    'round': number;
    /**
    * LatestTimestamp is available to some TEAL scripts. Defaults to the latest confirmed timestamp this algod is attached to.
    */
    'latestTimestamp': number;
    'sources': Array<DryrunSource>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "txns",
            "baseName": "txns",
            "type": "Array<string>",
            "format": "json"
        },
        {
            "name": "accounts",
            "baseName": "accounts",
            "type": "Array<Account>",
            "format": ""
        },
        {
            "name": "apps",
            "baseName": "apps",
            "type": "Array<Application>",
            "format": ""
        },
        {
            "name": "protocolVersion",
            "baseName": "protocol-version",
            "type": "string",
            "format": ""
        },
        {
            "name": "round",
            "baseName": "round",
            "type": "number",
            "format": ""
        },
        {
            "name": "latestTimestamp",
            "baseName": "latest-timestamp",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "sources",
            "baseName": "sources",
            "type": "Array<DryrunSource>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return DryrunRequest.attributeTypeMap;
    }

    public constructor() {
    }
}
