/**
 * Algod REST API.
 * API endpoint for algod operations.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: contact@algorand.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AccountStateDelta } from '../models/AccountStateDelta';
import { DryrunState } from '../models/DryrunState';
import { EvalDeltaKeyValue } from '../models/EvalDeltaKeyValue';
import { HttpFile } from '../http/http';

/**
* DryrunTxnResult contains any LogicSig or ApplicationCall program debug information and state updates from a dryrun.
*/
export class DryrunTxnResult {
    /**
    * Disassembled program line by line.
    */
    'disassembly': Array<string>;
    /**
    * Disassembled lsig program line by line.
    */
    'logicSigDisassembly'?: Array<string>;
    'logicSigTrace'?: Array<DryrunState>;
    'logicSigMessages'?: Array<string>;
    'appCallTrace'?: Array<DryrunState>;
    'appCallMessages'?: Array<string>;
    /**
    * Application state delta.
    */
    'globalDelta'?: Array<EvalDeltaKeyValue>;
    'localDeltas'?: Array<AccountStateDelta>;
    'logs'?: Array<string>;
    /**
    * Budget added during execution of app call transaction.
    */
    'budgetAdded'?: number;
    /**
    * Budget consumed during execution of app call transaction.
    */
    'budgetConsumed'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "disassembly",
            "baseName": "disassembly",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "logicSigDisassembly",
            "baseName": "logic-sig-disassembly",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "logicSigTrace",
            "baseName": "logic-sig-trace",
            "type": "Array<DryrunState>",
            "format": ""
        },
        {
            "name": "logicSigMessages",
            "baseName": "logic-sig-messages",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "appCallTrace",
            "baseName": "app-call-trace",
            "type": "Array<DryrunState>",
            "format": ""
        },
        {
            "name": "appCallMessages",
            "baseName": "app-call-messages",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "globalDelta",
            "baseName": "global-delta",
            "type": "Array<EvalDeltaKeyValue>",
            "format": ""
        },
        {
            "name": "localDeltas",
            "baseName": "local-deltas",
            "type": "Array<AccountStateDelta>",
            "format": ""
        },
        {
            "name": "logs",
            "baseName": "logs",
            "type": "Array<string>",
            "format": "byte"
        },
        {
            "name": "budgetAdded",
            "baseName": "budget-added",
            "type": "number",
            "format": ""
        },
        {
            "name": "budgetConsumed",
            "baseName": "budget-consumed",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return DryrunTxnResult.attributeTypeMap;
    }

    public constructor() {
    }
}
