/**
 * Algod REST API.
 * API endpoint for algod operations.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: contact@algorand.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { TealValue } from '../models/TealValue';
import { HttpFile } from '../http/http';

/**
* Stores the TEAL eval step data
*/
export class DryrunState {
    /**
    * Line number
    */
    'line': number;
    /**
    * Program counter
    */
    'pc': number;
    'stack': Array<TealValue>;
    'scratch'?: Array<TealValue>;
    /**
    * Evaluation error if any
    */
    'error'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "line",
            "baseName": "line",
            "type": "number",
            "format": ""
        },
        {
            "name": "pc",
            "baseName": "pc",
            "type": "number",
            "format": ""
        },
        {
            "name": "stack",
            "baseName": "stack",
            "type": "Array<TealValue>",
            "format": ""
        },
        {
            "name": "scratch",
            "baseName": "scratch",
            "type": "Array<TealValue>",
            "format": ""
        },
        {
            "name": "error",
            "baseName": "error",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return DryrunState.attributeTypeMap;
    }

    public constructor() {
    }
}
