/**
 * Algod REST API.
 * API endpoint for algod operations.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: contact@algorand.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* DryrunSource is TEAL source text that gets uploaded, compiled, and inserted into transactions or application state.
*/
export class DryrunSource {
    /**
    * FieldName is what kind of sources this is. If lsig then it goes into the transactions[this.TxnIndex].LogicSig. If approv or clearp it goes into the Approval Program or Clear State Program of application[this.AppIndex].
    */
    'fieldName': string;
    'source': string;
    'txnIndex': number;
    'appIndex': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "fieldName",
            "baseName": "field-name",
            "type": "string",
            "format": ""
        },
        {
            "name": "source",
            "baseName": "source",
            "type": "string",
            "format": ""
        },
        {
            "name": "txnIndex",
            "baseName": "txn-index",
            "type": "number",
            "format": ""
        },
        {
            "name": "appIndex",
            "baseName": "app-index",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return DryrunSource.attributeTypeMap;
    }

    public constructor() {
    }
}
