/**
 * Algod REST API.
 * API endpoint for algod operations.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: contact@algorand.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { EvalDelta } from '../models/EvalDelta';
import { HttpFile } from '../http/http';

/**
* Key-value pairs for StateDelta.
*/
export class EvalDeltaKeyValue {
    'key': string;
    'value': EvalDelta;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "key",
            "baseName": "key",
            "type": "string",
            "format": ""
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "EvalDelta",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return EvalDeltaKeyValue.attributeTypeMap;
    }

    public constructor() {
    }
}
