/**
 * Algod REST API.
 * API endpoint for algod operations.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: contact@algorand.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AppCallLogs } from '../models/AppCallLogs';
import { HttpFile } from '../http/http';

export class GetBlockLogs200Response {
    'logs': Array<AppCallLogs>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "logs",
            "baseName": "logs",
            "type": "Array<AppCallLogs>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GetBlockLogs200Response.attributeTypeMap;
    }

    public constructor() {
    }
}
