/**
 * Algod REST API.
 * API endpoint for algod operations.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: contact@algorand.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class GetBlock200Response {
    /**
    * Block header data.
    */
    'block': any;
    /**
    * Optional certificate object. This is only included when the format is set to message pack.
    */
    'cert'?: any;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "block",
            "baseName": "block",
            "type": "any",
            "format": ""
        },
        {
            "name": "cert",
            "baseName": "cert",
            "type": "any",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GetBlock200Response.attributeTypeMap;
    }

    public constructor() {
    }
}
