/**
 * Algod REST API.
 * API endpoint for algod operations.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: contact@algorand.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* PendingTransactions is an array of signed transactions exactly as they were submitted.
*/
export class GetPendingTransactionsByAddress200Response {
    /**
    * An array of signed transaction objects.
    */
    'topTransactions': Array<any>;
    /**
    * Total number of transactions in the pool.
    */
    'totalTransactions': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "topTransactions",
            "baseName": "top-transactions",
            "type": "Array<any>",
            "format": ""
        },
        {
            "name": "totalTransactions",
            "baseName": "total-transactions",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GetPendingTransactionsByAddress200Response.attributeTypeMap;
    }

    public constructor() {
    }
}
