/**
 * Algod REST API.
 * API endpoint for algod operations.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: contact@algorand.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Supply represents the current supply of MicroAlgos in the system
*/
export class GetSupply200Response {
    /**
    * Round
    */
    'currentRound': number;
    /**
    * OnlineMoney
    */
    'onlineMoney': number;
    /**
    * TotalMoney
    */
    'totalMoney': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "currentRound",
            "baseName": "current_round",
            "type": "number",
            "format": ""
        },
        {
            "name": "onlineMoney",
            "baseName": "online-money",
            "type": "number",
            "format": ""
        },
        {
            "name": "totalMoney",
            "baseName": "total-money",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GetSupply200Response.attributeTypeMap;
    }

    public constructor() {
    }
}
