/**
 * Algod REST API.
 * API endpoint for algod operations.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: contact@algorand.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { LedgerStateDeltaForTransactionGroup } from '../models/LedgerStateDeltaForTransactionGroup';
import { HttpFile } from '../http/http';

export class GetTransactionGroupLedgerStateDeltasForRound200Response {
    'deltas': Array<LedgerStateDeltaForTransactionGroup>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "deltas",
            "baseName": "Deltas",
            "type": "Array<LedgerStateDeltaForTransactionGroup>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GetTransactionGroupLedgerStateDeltasForRound200Response.attributeTypeMap;
    }

    public constructor() {
    }
}
