/**
 * Algod REST API.
 * API endpoint for algod operations.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: contact@algorand.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class GetTransactionProof200Response {
    /**
    * Proof of transaction membership.
    */
    'proof': string;
    /**
    * Hash of SignedTxnInBlock for verifying proof.
    */
    'stibhash': string;
    /**
    * Represents the depth of the tree that is being proven, i.e. the number of edges from a leaf to the root.
    */
    'treedepth': number;
    /**
    * Index of the transaction in the block\'s payset.
    */
    'idx': number;
    /**
    * The type of hash function used to create the proof, must be one of:  * sha512_256  * sha256
    */
    'hashtype': GetTransactionProof200ResponseHashtypeEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "proof",
            "baseName": "proof",
            "type": "string",
            "format": "byte"
        },
        {
            "name": "stibhash",
            "baseName": "stibhash",
            "type": "string",
            "format": "byte"
        },
        {
            "name": "treedepth",
            "baseName": "treedepth",
            "type": "number",
            "format": ""
        },
        {
            "name": "idx",
            "baseName": "idx",
            "type": "number",
            "format": ""
        },
        {
            "name": "hashtype",
            "baseName": "hashtype",
            "type": "GetTransactionProof200ResponseHashtypeEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GetTransactionProof200Response.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum GetTransactionProof200ResponseHashtypeEnum {
    Sha512256 = 'sha512_256',
    Sha256 = 'sha256'
}

