/**
 * Algod REST API.
 * API endpoint for algod operations.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: contact@algorand.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Contains a ledger delta for a single transaction group
*/
export class LedgerStateDeltaForTransactionGroup {
    /**
    * Ledger StateDelta object
    */
    'delta': any;
    'ids': Array<string>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "delta",
            "baseName": "Delta",
            "type": "any",
            "format": ""
        },
        {
            "name": "ids",
            "baseName": "Ids",
            "type": "Array<string>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return LedgerStateDeltaForTransactionGroup.attributeTypeMap;
    }

    public constructor() {
    }
}
