/**
 * Algod REST API.
 * API endpoint for algod operations.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: contact@algorand.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Proof of membership and position of a light block header.
*/
export class LightBlockHeaderProof {
    /**
    * The index of the light block header in the vector commitment tree
    */
    'index': number;
    /**
    * Represents the depth of the tree that is being proven, i.e. the number of edges from a leaf to the root.
    */
    'treedepth': number;
    /**
    * The encoded proof.
    */
    'proof': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "index",
            "baseName": "index",
            "type": "number",
            "format": ""
        },
        {
            "name": "treedepth",
            "baseName": "treedepth",
            "type": "number",
            "format": ""
        },
        {
            "name": "proof",
            "baseName": "proof",
            "type": "string",
            "format": "byte"
        }    ];

    static getAttributeTypeMap() {
        return LightBlockHeaderProof.attributeTypeMap;
    }

    public constructor() {
    }
}
