/**
 * Algod REST API.
 * API endpoint for algod operations.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: contact@algorand.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AccountParticipation } from '../models/AccountParticipation';
import { HttpFile } from '../http/http';

/**
* Represents a participation key used by the node.
*/
export class ParticipationKey {
    /**
    * The key\'s ParticipationID.
    */
    'id': string;
    /**
    * Address the key was generated for.
    */
    'address': string;
    /**
    * When registered, this is the first round it may be used.
    */
    'effectiveFirstValid'?: number;
    /**
    * When registered, this is the last round it may be used.
    */
    'effectiveLastValid'?: number;
    /**
    * Round when this key was last used to vote.
    */
    'lastVote'?: number;
    /**
    * Round when this key was last used to propose a block.
    */
    'lastBlockProposal'?: number;
    /**
    * Round when this key was last used to generate a state proof.
    */
    'lastStateProof'?: number;
    'key': AccountParticipation;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "address",
            "baseName": "address",
            "type": "string",
            "format": ""
        },
        {
            "name": "effectiveFirstValid",
            "baseName": "effective-first-valid",
            "type": "number",
            "format": ""
        },
        {
            "name": "effectiveLastValid",
            "baseName": "effective-last-valid",
            "type": "number",
            "format": ""
        },
        {
            "name": "lastVote",
            "baseName": "last-vote",
            "type": "number",
            "format": ""
        },
        {
            "name": "lastBlockProposal",
            "baseName": "last-block-proposal",
            "type": "number",
            "format": ""
        },
        {
            "name": "lastStateProof",
            "baseName": "last-state-proof",
            "type": "number",
            "format": ""
        },
        {
            "name": "key",
            "baseName": "key",
            "type": "AccountParticipation",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ParticipationKey.attributeTypeMap;
    }

    public constructor() {
    }
}
