/**
 * Algod REST API.
 * API endpoint for algod operations.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: contact@algorand.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AccountStateDelta } from '../models/AccountStateDelta';
import { EvalDeltaKeyValue } from '../models/EvalDeltaKeyValue';
import { HttpFile } from '../http/http';

/**
* Details about a pending transaction. If the transaction was recently confirmed, includes confirmation details like the round and reward details.
*/
export class PendingTransactionResponse {
    /**
    * The asset index if the transaction was found and it created an asset.
    */
    'assetIndex'?: number;
    /**
    * The application index if the transaction was found and it created an application.
    */
    'applicationIndex'?: number;
    /**
    * Rewards in microalgos applied to the close remainder to account.
    */
    'closeRewards'?: number;
    /**
    * Closing amount for the transaction.
    */
    'closingAmount'?: number;
    /**
    * The number of the asset\'s unit that were transferred to the close-to address.
    */
    'assetClosingAmount'?: number;
    /**
    * The round where this transaction was confirmed, if present.
    */
    'confirmedRound'?: number;
    /**
    * Indicates that the transaction was kicked out of this node\'s transaction pool (and specifies why that happened).  An empty string indicates the transaction wasn\'t kicked out of this node\'s txpool due to an error. 
    */
    'poolError': string;
    /**
    * Rewards in microalgos applied to the receiver account.
    */
    'receiverRewards'?: number;
    /**
    * Rewards in microalgos applied to the sender account.
    */
    'senderRewards'?: number;
    /**
    * Local state key/value changes for the application being executed by this transaction.
    */
    'localStateDelta'?: Array<AccountStateDelta>;
    /**
    * Application state delta.
    */
    'globalStateDelta'?: Array<EvalDeltaKeyValue>;
    /**
    * Logs for the application being executed by this transaction.
    */
    'logs'?: Array<string>;
    /**
    * Inner transactions produced by application execution.
    */
    'innerTxns'?: Array<PendingTransactionResponse>;
    /**
    * The raw signed transaction.
    */
    'txn': any;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "assetIndex",
            "baseName": "asset-index",
            "type": "number",
            "format": ""
        },
        {
            "name": "applicationIndex",
            "baseName": "application-index",
            "type": "number",
            "format": ""
        },
        {
            "name": "closeRewards",
            "baseName": "close-rewards",
            "type": "number",
            "format": ""
        },
        {
            "name": "closingAmount",
            "baseName": "closing-amount",
            "type": "number",
            "format": ""
        },
        {
            "name": "assetClosingAmount",
            "baseName": "asset-closing-amount",
            "type": "number",
            "format": ""
        },
        {
            "name": "confirmedRound",
            "baseName": "confirmed-round",
            "type": "number",
            "format": ""
        },
        {
            "name": "poolError",
            "baseName": "pool-error",
            "type": "string",
            "format": ""
        },
        {
            "name": "receiverRewards",
            "baseName": "receiver-rewards",
            "type": "number",
            "format": ""
        },
        {
            "name": "senderRewards",
            "baseName": "sender-rewards",
            "type": "number",
            "format": ""
        },
        {
            "name": "localStateDelta",
            "baseName": "local-state-delta",
            "type": "Array<AccountStateDelta>",
            "format": ""
        },
        {
            "name": "globalStateDelta",
            "baseName": "global-state-delta",
            "type": "Array<EvalDeltaKeyValue>",
            "format": ""
        },
        {
            "name": "logs",
            "baseName": "logs",
            "type": "Array<string>",
            "format": "byte"
        },
        {
            "name": "innerTxns",
            "baseName": "inner-txns",
            "type": "Array<PendingTransactionResponse>",
            "format": ""
        },
        {
            "name": "txn",
            "baseName": "txn",
            "type": "any",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PendingTransactionResponse.attributeTypeMap;
    }

    public constructor() {
    }
}
