/**
 * Algod REST API.
 * API endpoint for algod operations.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: contact@algorand.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AvmValue } from '../models/AvmValue';
import { HttpFile } from '../http/http';

/**
* A write operation into a scratch slot.
*/
export class ScratchChange {
    /**
    * The scratch slot written.
    */
    'slot': number;
    'newValue': AvmValue;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "slot",
            "baseName": "slot",
            "type": "number",
            "format": ""
        },
        {
            "name": "newValue",
            "baseName": "new-value",
            "type": "AvmValue",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ScratchChange.attributeTypeMap;
    }

    public constructor() {
    }
}
