/**
 * Algod REST API.
 * API endpoint for algod operations.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: contact@algorand.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ApplicationStateOperation } from '../models/ApplicationStateOperation';
import { AvmValue } from '../models/AvmValue';
import { ScratchChange } from '../models/ScratchChange';
import { HttpFile } from '../http/http';

/**
* The set of trace information and effect from evaluating a single opcode.
*/
export class SimulationOpcodeTraceUnit {
    /**
    * The program counter of the current opcode being evaluated.
    */
    'pc': number;
    /**
    * The writes into scratch slots.
    */
    'scratchChanges'?: Array<ScratchChange>;
    /**
    * The operations against the current application\'s states.
    */
    'stateChanges'?: Array<ApplicationStateOperation>;
    /**
    * The indexes of the traces for inner transactions spawned by this opcode, if any.
    */
    'spawnedInners'?: Array<number>;
    /**
    * The number of deleted stack values by this opcode.
    */
    'stackPopCount'?: number;
    /**
    * The values added by this opcode to the stack.
    */
    'stackAdditions'?: Array<AvmValue>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "pc",
            "baseName": "pc",
            "type": "number",
            "format": ""
        },
        {
            "name": "scratchChanges",
            "baseName": "scratch-changes",
            "type": "Array<ScratchChange>",
            "format": ""
        },
        {
            "name": "stateChanges",
            "baseName": "state-changes",
            "type": "Array<ApplicationStateOperation>",
            "format": ""
        },
        {
            "name": "spawnedInners",
            "baseName": "spawned-inners",
            "type": "Array<number>",
            "format": ""
        },
        {
            "name": "stackPopCount",
            "baseName": "stack-pop-count",
            "type": "number",
            "format": ""
        },
        {
            "name": "stackAdditions",
            "baseName": "stack-additions",
            "type": "Array<AvmValue>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SimulationOpcodeTraceUnit.attributeTypeMap;
    }

    public constructor() {
    }
}
