/**
 * Algod REST API.
 * API endpoint for algod operations.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: contact@algorand.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* The set of parameters and limits override during simulation. If this set of parameters is present, then evaluation parameters may differ from standard evaluation in certain ways.
*/
export class SimulationEvalOverrides {
    /**
    * If true, transactions without signatures are allowed and simulated as if they were properly signed.
    */
    'allowEmptySignatures'?: boolean;
    /**
    * If true, allows access to unnamed resources during simulation.
    */
    'allowUnnamedResources'?: boolean;
    /**
    * The maximum log calls one can make during simulation
    */
    'maxLogCalls'?: number;
    /**
    * The maximum byte number to log during simulation
    */
    'maxLogSize'?: number;
    /**
    * The extra opcode budget added to each transaction group during simulation
    */
    'extraOpcodeBudget'?: number;
    /**
    * If true, signers for transactions that are missing signatures will be fixed during evaluation.
    */
    'fixSigners'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "allowEmptySignatures",
            "baseName": "allow-empty-signatures",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "allowUnnamedResources",
            "baseName": "allow-unnamed-resources",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "maxLogCalls",
            "baseName": "max-log-calls",
            "type": "number",
            "format": ""
        },
        {
            "name": "maxLogSize",
            "baseName": "max-log-size",
            "type": "number",
            "format": ""
        },
        {
            "name": "extraOpcodeBudget",
            "baseName": "extra-opcode-budget",
            "type": "number",
            "format": ""
        },
        {
            "name": "fixSigners",
            "baseName": "fix-signers",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SimulationEvalOverrides.attributeTypeMap;
    }

    public constructor() {
    }
}
