/**
 * Algod REST API.
 * API endpoint for algod operations.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: contact@algorand.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ApplicationInitialStates } from '../models/ApplicationInitialStates';
import { HttpFile } from '../http/http';

/**
* Initial states of resources that were accessed during simulation.
*/
export class SimulateInitialStates {
    /**
    * The initial states of accessed application before simulation. The order of this array is arbitrary.
    */
    'appInitialStates'?: Array<ApplicationInitialStates>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "appInitialStates",
            "baseName": "app-initial-states",
            "type": "Array<ApplicationInitialStates>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SimulateInitialStates.attributeTypeMap;
    }

    public constructor() {
    }
}
