/**
 * Algod REST API.
 * API endpoint for algod operations.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: contact@algorand.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ApplicationLocalReference } from '../models/ApplicationLocalReference';
import { AssetHoldingReference } from '../models/AssetHoldingReference';
import { BoxReference } from '../models/BoxReference';
import { HttpFile } from '../http/http';

/**
* These are resources that were accessed by this group that would normally have caused failure, but were allowed in simulation. Depending on where this object is in the response, the unnamed resources it contains may or may not qualify for group resource sharing. If this is a field in SimulateTransactionGroupResult, the resources do qualify, but if this is a field in SimulateTransactionResult, they do not qualify. In order to make this group valid for actual submission, resources that qualify for group sharing can be made available by any transaction of the group; otherwise, resources must be placed in the same transaction which accessed them.
*/
export class SimulateUnnamedResourcesAccessed {
    /**
    * The unnamed accounts that were referenced. The order of this array is arbitrary.
    */
    'accounts'?: Array<string>;
    /**
    * The unnamed assets that were referenced. The order of this array is arbitrary.
    */
    'assets'?: Array<number>;
    /**
    * The unnamed applications that were referenced. The order of this array is arbitrary.
    */
    'apps'?: Array<number>;
    /**
    * The unnamed boxes that were referenced. The order of this array is arbitrary.
    */
    'boxes'?: Array<BoxReference>;
    /**
    * The number of extra box references used to increase the IO budget. This is in addition to the references defined in the input transaction group and any referenced to unnamed boxes.
    */
    'extraBoxRefs'?: number;
    /**
    * The unnamed asset holdings that were referenced. The order of this array is arbitrary.
    */
    'assetHoldings'?: Array<AssetHoldingReference>;
    /**
    * The unnamed application local states that were referenced. The order of this array is arbitrary.
    */
    'appLocals'?: Array<ApplicationLocalReference>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "accounts",
            "baseName": "accounts",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "assets",
            "baseName": "assets",
            "type": "Array<number>",
            "format": ""
        },
        {
            "name": "apps",
            "baseName": "apps",
            "type": "Array<number>",
            "format": ""
        },
        {
            "name": "boxes",
            "baseName": "boxes",
            "type": "Array<BoxReference>",
            "format": ""
        },
        {
            "name": "extraBoxRefs",
            "baseName": "extra-box-refs",
            "type": "number",
            "format": ""
        },
        {
            "name": "assetHoldings",
            "baseName": "asset-holdings",
            "type": "Array<AssetHoldingReference>",
            "format": ""
        },
        {
            "name": "appLocals",
            "baseName": "app-locals",
            "type": "Array<ApplicationLocalReference>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SimulateUnnamedResourcesAccessed.attributeTypeMap;
    }

    public constructor() {
    }
}
