/**
 * Algod REST API.
 * API endpoint for algod operations.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: contact@algorand.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* An object that configures simulation execution trace.
*/
export class SimulateTraceConfig {
    /**
    * A boolean option for opting in execution trace features simulation endpoint.
    */
    'enable'?: boolean;
    /**
    * A boolean option enabling returning stack changes together with execution trace during simulation.
    */
    'stackChange'?: boolean;
    /**
    * A boolean option enabling returning scratch slot changes together with execution trace during simulation.
    */
    'scratchChange'?: boolean;
    /**
    * A boolean option enabling returning application state changes (global, local, and box changes) with the execution trace during simulation.
    */
    'stateChange'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "enable",
            "baseName": "enable",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "stackChange",
            "baseName": "stack-change",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "scratchChange",
            "baseName": "scratch-change",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "stateChange",
            "baseName": "state-change",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SimulateTraceConfig.attributeTypeMap;
    }

    public constructor() {
    }
}
