/**
 * Algod REST API.
 * API endpoint for algod operations.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: contact@algorand.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* A transaction group to simulate.
*/
export class SimulateRequestTransactionGroup {
    /**
    * An atomic transaction group.
    */
    'txns': Array<string>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "txns",
            "baseName": "txns",
            "type": "Array<string>",
            "format": "json"
        }    ];

    static getAttributeTypeMap() {
        return SimulateRequestTransactionGroup.attributeTypeMap;
    }

    public constructor() {
    }
}
