/**
 * Algod REST API.
 * API endpoint for algod operations.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: contact@algorand.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PendingTransactionResponse } from '../models/PendingTransactionResponse';
import { SimulateUnnamedResourcesAccessed } from '../models/SimulateUnnamedResourcesAccessed';
import { SimulationTransactionExecTrace } from '../models/SimulationTransactionExecTrace';
import { HttpFile } from '../http/http';

/**
* Simulation result for an individual transaction
*/
export class SimulateTransactionResult {
    'txnResult': PendingTransactionResponse;
    /**
    * Budget used during execution of an app call transaction. This value includes budged used by inner app calls spawned by this transaction.
    */
    'appBudgetConsumed'?: number;
    /**
    * Budget used during execution of a logic sig transaction.
    */
    'logicSigBudgetConsumed'?: number;
    'execTrace'?: SimulationTransactionExecTrace;
    'unnamedResourcesAccessed'?: SimulateUnnamedResourcesAccessed;
    /**
    * The account that needed to sign this transaction when no signature was provided and the provided signer was incorrect.
    */
    'fixedSigner'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "txnResult",
            "baseName": "txn-result",
            "type": "PendingTransactionResponse",
            "format": ""
        },
        {
            "name": "appBudgetConsumed",
            "baseName": "app-budget-consumed",
            "type": "number",
            "format": ""
        },
        {
            "name": "logicSigBudgetConsumed",
            "baseName": "logic-sig-budget-consumed",
            "type": "number",
            "format": ""
        },
        {
            "name": "execTrace",
            "baseName": "exec-trace",
            "type": "SimulationTransactionExecTrace",
            "format": ""
        },
        {
            "name": "unnamedResourcesAccessed",
            "baseName": "unnamed-resources-accessed",
            "type": "SimulateUnnamedResourcesAccessed",
            "format": ""
        },
        {
            "name": "fixedSigner",
            "baseName": "fixed-signer",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SimulateTransactionResult.attributeTypeMap;
    }

    public constructor() {
    }
}
