/**
 * Algod REST API.
 * API endpoint for algod operations.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: contact@algorand.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SimulateTransactionResult } from '../models/SimulateTransactionResult';
import { SimulateUnnamedResourcesAccessed } from '../models/SimulateUnnamedResourcesAccessed';
import { HttpFile } from '../http/http';

/**
* Simulation result for an atomic transaction group
*/
export class SimulateTransactionGroupResult {
    /**
    * Simulation result for individual transactions
    */
    'txnResults': Array<SimulateTransactionResult>;
    /**
    * If present, indicates that the transaction group failed and specifies why that happened
    */
    'failureMessage'?: string;
    /**
    * If present, indicates which transaction in this group caused the failure. This array represents the path to the failing transaction. Indexes are zero based, the first element indicates the top-level transaction, and successive elements indicate deeper inner transactions.
    */
    'failedAt'?: Array<number>;
    /**
    * Total budget added during execution of app calls in the transaction group.
    */
    'appBudgetAdded'?: number;
    /**
    * Total budget consumed during execution of app calls in the transaction group.
    */
    'appBudgetConsumed'?: number;
    'unnamedResourcesAccessed'?: SimulateUnnamedResourcesAccessed;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "txnResults",
            "baseName": "txn-results",
            "type": "Array<SimulateTransactionResult>",
            "format": ""
        },
        {
            "name": "failureMessage",
            "baseName": "failure-message",
            "type": "string",
            "format": ""
        },
        {
            "name": "failedAt",
            "baseName": "failed-at",
            "type": "Array<number>",
            "format": ""
        },
        {
            "name": "appBudgetAdded",
            "baseName": "app-budget-added",
            "type": "number",
            "format": ""
        },
        {
            "name": "appBudgetConsumed",
            "baseName": "app-budget-consumed",
            "type": "number",
            "format": ""
        },
        {
            "name": "unnamedResourcesAccessed",
            "baseName": "unnamed-resources-accessed",
            "type": "SimulateUnnamedResourcesAccessed",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SimulateTransactionGroupResult.attributeTypeMap;
    }

    public constructor() {
    }
}
