/**
 * Algod REST API.
 * API endpoint for algod operations.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: contact@algorand.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { StateProofMessage } from '../models/StateProofMessage';
import { HttpFile } from '../http/http';

/**
* Represents a state proof and its corresponding message
*/
export class StateProof {
    'message': StateProofMessage;
    /**
    * The encoded StateProof for the message.
    */
    'stateProof': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "message",
            "baseName": "Message",
            "type": "StateProofMessage",
            "format": ""
        },
        {
            "name": "stateProof",
            "baseName": "StateProof",
            "type": "string",
            "format": "byte"
        }    ];

    static getAttributeTypeMap() {
        return StateProof.attributeTypeMap;
    }

    public constructor() {
    }
}
