/**
 * Algod REST API.
 * API endpoint for algod operations.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: contact@algorand.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Represents a TEAL value.
*/
export class TealValue {
    /**
    * \\[tt\\] value type. Value `1` refers to **bytes**, value `2` refers to **uint**
    */
    'type': number;
    /**
    * \\[tb\\] bytes value.
    */
    'bytes': string;
    /**
    * \\[ui\\] uint value.
    */
    'uint': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "number",
            "format": ""
        },
        {
            "name": "bytes",
            "baseName": "bytes",
            "type": "string",
            "format": ""
        },
        {
            "name": "uint",
            "baseName": "uint",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return TealValue.attributeTypeMap;
    }

    public constructor() {
    }
}
