/**
 * Algod REST API.
 * API endpoint for algod operations.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: contact@algorand.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { DryrunTxnResult } from '../models/DryrunTxnResult';
import { HttpFile } from '../http/http';

export class TealDryrun200Response {
    'txns': Array<DryrunTxnResult>;
    'error': string;
    /**
    * Protocol version is the protocol version Dryrun was operated under.
    */
    'protocolVersion': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "txns",
            "baseName": "txns",
            "type": "Array<DryrunTxnResult>",
            "format": ""
        },
        {
            "name": "error",
            "baseName": "error",
            "type": "string",
            "format": ""
        },
        {
            "name": "protocolVersion",
            "baseName": "protocol-version",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return TealDryrun200Response.attributeTypeMap;
    }

    public constructor() {
    }
}
