/**
 * Algod REST API.
 * API endpoint for algod operations.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: contact@algorand.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { TealValue } from '../models/TealValue';
import { HttpFile } from '../http/http';

/**
* Represents a key-value pair in an application store.
*/
export class TealKeyValue {
    'key': string;
    'value': TealValue;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "key",
            "baseName": "key",
            "type": "string",
            "format": ""
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "TealValue",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return TealKeyValue.attributeTypeMap;
    }

    public constructor() {
    }
}
