/**
 * Algod REST API.
 * API endpoint for algod operations.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: contact@algorand.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class TealCompile200Response {
    /**
    * base32 SHA512_256 of program bytes (Address style)
    */
    'hash': string;
    /**
    * base64 encoded program bytes
    */
    'result': string;
    /**
    * JSON of the source map
    */
    'sourcemap'?: any;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "hash",
            "baseName": "hash",
            "type": "string",
            "format": ""
        },
        {
            "name": "result",
            "baseName": "result",
            "type": "string",
            "format": ""
        },
        {
            "name": "sourcemap",
            "baseName": "sourcemap",
            "type": "any",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return TealCompile200Response.attributeTypeMap;
    }

    public constructor() {
    }
}
