/**
 * Algod REST API.
 * API endpoint for algod operations.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: contact@algorand.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* TransactionParams contains the parameters that help a client construct a new transaction.
*/
export class TransactionParams200Response {
    /**
    * ConsensusVersion indicates the consensus protocol version as of LastRound.
    */
    'consensusVersion': string;
    /**
    * Fee is the suggested transaction fee Fee is in units of micro-Algos per byte. Fee may fall to zero but transactions must still have a fee of at least MinTxnFee for the current network protocol.
    */
    'fee': number;
    /**
    * GenesisHash is the hash of the genesis block.
    */
    'genesisHash': string;
    /**
    * GenesisID is an ID listed in the genesis block.
    */
    'genesisId': string;
    /**
    * LastRound indicates the last round seen
    */
    'lastRound': number;
    /**
    * The minimum transaction fee (not per byte) required for the txn to validate for the current network protocol.
    */
    'minFee': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "consensusVersion",
            "baseName": "consensus-version",
            "type": "string",
            "format": ""
        },
        {
            "name": "fee",
            "baseName": "fee",
            "type": "number",
            "format": ""
        },
        {
            "name": "genesisHash",
            "baseName": "genesis-hash",
            "type": "string",
            "format": "byte"
        },
        {
            "name": "genesisId",
            "baseName": "genesis-id",
            "type": "string",
            "format": ""
        },
        {
            "name": "lastRound",
            "baseName": "last-round",
            "type": "number",
            "format": ""
        },
        {
            "name": "minFee",
            "baseName": "min-fee",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return TransactionParams200Response.attributeTypeMap;
    }

    public constructor() {
    }
}
