name: API Clients CI
# TODO: NC - Delete this workflow when done

on:
  # pull_request:
  #   branches: [main]
  #   paths:
  #     - "api/**"
  #     - ".github/workflows/api_clients_ci.yml"
  workflow_dispatch:

env:
  CRATE: algokit_transact

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Setup api tools
        working-directory: api
        run: bun install

      - name: Generate algod clients
        working-directory: api
        run: bun run generate:algod_api:all

      - name: Check generated clients have been reviewed
        shell: bash
        run: |
          # Add untracked files as empty so they come up in diff
          git add -N ./packages/**/algod_api
          # Look for changes in generated templates and error if there are any
          git diff --exit-code --minimal ./packages/**/algod_api

      - name: Upload algod TypeScript client
        uses: actions/upload-artifact@v4
        with:
          name: algokit-algod-api-ts
          path: packages/typescript/algod_api
          retention-days: 1

      - name: Upload algod Python client
        uses: actions/upload-artifact@v4
        with:
          name: algokit-algod-api-py
          path: packages/python/algod_api
          retention-days: 1

  algokit-algod-api-ts:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.85.0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Download algod TypeScript client
        uses: actions/download-artifact@v4
        with:
          name: algokit-algod-api-ts
          path: packages/typescript/algod_api

      - name: Install AlgoKit
        run: pipx install algokit

      - name: Start localnet
        run: algokit localnet start

      - name: Build TypeScript ffi package
        run: bun scripts/build ${{ env.CRATE }} typescript

      - name: Test algod TypeScript client
        working-directory: packages/typescript/algod_api
        run: |
          bun install
          bun run test

  algokit-algod-api-py:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.85.0

      - name: Download algod Python client
        uses: actions/download-artifact@v4
        with:
          name: algokit-algod-api-py
          path: packages/typescript/algod_api

      - name: Install AlgoKit
        run: pipx install algokit

      - name: Start localnet
        run: algokit localnet start

      - name: Install poetry
        run: pipx install poetry

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Test algod Python client
        working-directory: packages/python/algod_api
        run: |
          poetry install
          poetry run pytest
